### ISSUE TITLE
[S] DUP admin  on pass search page if user clicks enter on keyboard it clears search instead of submit

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-reso-admin#297]
### **How to replicate:**

- go to DUP admin (prod or test)
- 
- go to pass search
- 
- put in some filters or criteria
- 
- click enter

- the enter click is clearing all search criteria - this is not expected behavior

### **Expected Behavior:**

- enter click on keyboard should submit search

### **Notes**

**Comment by JLWade** [comment]
working for me as expected - can move to done and prod
