### ISSUE TITLE
DUP - Admin Pass search does not filter data when the date is not selected

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-admin#305]
**How to replicate:**

- Navigate to the PROD DUP Admin and navigate to the pass search page
- Select a date a park, a facility and a pass type and click search
- Now notice one of the pass holder’s first name and add it to the first name field and click search → Results should filter.
- Then remove the date filter and click search
- Check if you get the results for that first name

**Expected Behavior:**

- If the date field is not mandatory then results should be filtered with respect to the selected filters.

**Issue:**

- If the date field is empty no results are displayed. Instead, it shows a Load more button which does nothing. 

Refer to the video:
https://github.com/bcgov/parks-data-register/assets/145403218/5fda7f26-cf3f-4656-ac3d-ba702a6b120b

**Linked Issues:**
[](https://github.com/bcgov/parks-reso-admin/issues/306)
#306

**Comment by LindsayMacfarlane** [comment]
November 21, 2024 - DUP prioritization session. This ticket/issue was identified as high priority.

https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* When the date field is cleared and searched without the date filter, the results section shows results accurately. 
* Moving to Done.
