### ISSUE TITLE
DUP Admin - empty links in menu

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-admin#308]
## Description
How to replicate:
1. Log into DUP Admin
2. Hover over the left-hand menu below the metrics link:

    ![Image](https://github.com/bcgov/parks-reso-admin/assets/145403218/9aa1c3ed-7fd1-4040-aa0d-9b115721501c)

## Expected Behavior
* There shouldn’t be any empty links in the menu

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed.
