### ISSUE TITLE
[M] Editable FAQ page on DUP Admin

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-admin#325]
As a BC Parks staff DUP admin user, I want to easily update the FAQ so that I can proactively address incoming questions from the public.

The purpose of this FAQ page is to reduce the number of questions and inquiries coming in to park info by proactively supplying more information up front. This page should be editable by sys admin users only.

Since this page is not related to a specific park it will have it's own left nav component as it is site wide.

![Image](https://github.com/bcgov/parks-reso-admin/assets/26172886/57347c92-2257-41a1-a2b4-e09389cc1497)

**Acceptance Criteria:**
- FAQ Page exists in DUP Admin
  - Only sysadmin role can access this page
  - FAQ page will open in a new tab
  - FAQ is added to the left nav

![Image](https://github.com/bcgov/parks-reso-admin/assets/26172886/426084e4-e34e-4de2-b684-2a1da5c86865)

- Editable text component used on park description (tiny mce currently used in DUP admin on park details page) is set up on FAQ page for user to add, edit, change, delete FAQ text, this include 
  - same functionality available: formating text size, font, color, hyperlinks, etc.
- user can save edits or cancel changes and these will save and display on DUP public 
- user will receive a success or error toast on save
https://github.com/bcgov/parks-reso-public/issues/289

Notes:

**Comment by manuji** [comment]
@Christopher-walsh22 , when I get to the FAQ page on TEST, I get an error message and I see console errors as well. Assigning this back to you. 

![Image](https://github.com/bcgov/parks-reso-admin/assets/65190263/442c7849-0dc0-4dc7-a05a-b3b43b4b47e6)

**Comment by manuji** [comment]
Tested on TEST: **Done**

* This feature has been tested and separate tickets have been created for the issues. 
https://github.com/bcgov/parks-reso-admin/issues/334
https://github.com/bcgov/parks-reso-admin/issues/335
https://github.com/bcgov/parks-reso-admin/issues/336
https://github.com/bcgov/parks-reso-admin/issues/337

* passing this to PO review as the feature has been implemented. 

Link to Figma: https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3655%3A13289&mode=design&t=AAEyjwUKrPkhHGOz-1

**Comment by JLWade** [comment]
Moving this one to done as editing works - Chris resolving #334, #335 and 336 and 337 moved into another sprint

**Comment by manuji** [comment]
Tested on TEST: Pending
* Verified that the FAQ page on the Admin system is only accessible by the "sysAdmin" role.
* But the link to FAQ page is displayed on both Left nav and the Home page for the non-subsAdmin users. 

@JLWade  & @ndelraye, shouldn't we hide the links if they are not relevant to the logged-in user? Please let us know your thoughts. 

Fyi @Christopher-walsh22

**Comment by manuji** [comment]
Closing this ticket as it should be.
