### ISSUE TITLE
DUP- Admin-> FAQ page does not open in a new tab

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-admin#334]
Parent ticket: https://github.com/bcgov/parks-reso-admin/issues/325

Scenario:
* Navigate to the DUP-Admin on TEST environment: https://d3jkh5unv9de6y.cloudfront.net/dayuse/
* Login as an sysAdmin user
* From both Home page and from the left navigation menu select the link to access the FAQ page. 

Expected:
* As per the requirements and AC given on https://d3jkh5unv9de6y.cloudfront.net/dayuse/, the FAQ page should open in a new tab. 

Issue:
* The page does not open in a new tab.

**Comment by Christopher-walsh22** [comment]
@ndelraye Just want to confirm that this required for the admin side. After a user has logged in it seems odd to be opening restricted components in new tabs. This functionality does not match the load of other components through admin.

**Comment by ndelraye** [comment]
@Christopher-walsh22 I agree with you on the admin side it does not need to pen in a new tab

**Comment by manuji** [comment]
Thanks @Christopher-walsh22 & @ndelraye , I will close this ticket.
