### ISSUE TITLE
[M] Admin side - Ability to set a Special Closure on a park

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-admin#346]
#### Description:

As an admin user, I want to be able to set a Special Closure notice on a park in DUP so that the Public cannot book a DUP during special closure dates.

more info: https://bcgov.sharepoint.com/:w:/r/teams/08548/_layouts/15/Doc.aspx?sourcedoc=%7B6BF96516-551C-4FA0-AA65-4E5ACFB03C7F%7D&file=DUP%20-%20Special%20Closures.docx&action=default&mobileredirect=true

#### Acceptance Criteria:

Given that I am a DUP admin user, 
When I go to the park edit page 
Then I see a toggle for special closure.

Given that I am a DUP admin user, 
When I toggle park status to "special closure"
Then a wysiwyg text box opens where I can type in a message for the public page. 

Given that I am a DUP admin user, 
When I save the special closure edits on the park edit page,
Then the park has new status of special closure and greys out "passes required" status toggle.

#### Development Checklist:

- [ ] API endpoint updated on park level to include flag for `specialClosure` handling
- [ ] Public front-end api call is updated to gather the `specialClosure` logic
- [ ] Toggle added for `specialClosure`
- [ ] Wysiwyg added for `specialClosure` text
- [ ] When saving park information `specialClosure` status and text is saved to DB
- [ ] UT's written

#### Dependencies

- Blocked by #347 
- Blocking
- for first iteration of this we will not have any dates specified to automate on/off of closure and will manually set status and deal wtih passes available booking times through facilities

**Wireframe(s):**
https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3818%3A10794&mode=design&t=L5nXhQRNpft46BFs-1

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Christopher-walsh22** [comment]
Can any help me understand this AC:

"Given that I am a DUP admin user,
When I save the special closure edits on the park edit page,
Then the park has new status of special closure and greys out "passes required" status toggle."

I thought there was a need to have the ability for special closure on a park but still be able to book tickets for a future on public side. If special closure makes tickets unavailable that would not be possible. Is it better to have the special closure toggle not effect the requirement for tickets? If an admin has the ability to set both independently we could have the special closure notice active on public side but still allow users to click into the park to book in advance of the park reopening (the two day window we discussed).  I may have missed a discussion in my notes, please let me know :) 

@cameronpettit  @Dianadec  @JLWade

**Comment by cameronpettit** [comment]
We tried suggesting that the special closure notice just be available to fill out if you close the park (similar to what we do on the facility edit side of things) but as you've discovered, it wasn't so easily coupled together in that way. I like the idea that the special closure notice is just that - a notice. Leave the closing of the park up to the existing park closure feature and trust that the admin will do both. I don't remember if that specific point was brought up at refinement.

My understanding from refinement last week was that from an administrative standpoint, closing the park and setting a special closure notice were mutually exclusive actions anyways. If you want to show a special closure, you fill one out on the admin side. If you also want to close the park, you use the existing park closure feature. Combining the two creates the desired effect on the public facing site. If you have a special closure, the front end language changes whether the park is closed or not. 

@Dianadec @JLWade correct me if I am wrong - I think if this is a somewhat urgent feature, we implement it the way @Christopher-walsh22 has suggested.

**Comment by JLWade** [comment]
Ya I like this idea - just need to clarify the public side UI logic. 
- if special closure is turned on then notice is shown and park is not greyed out
- if passes required is toggled on then book pass button shows
- if passes required is toggled off AND special closure is turned on then park is not greyed out but book pass button is gone (does it show two status's and dots or does special closure only show? @Christopher-walsh22 @ndelraye )
- if passes required is toggled on AND special closure is turned on then park is not greyed out out and book passes button is available (similar question to above?)
any other thoughts? @Dianadec @cameronpettit

**Comment by Christopher-walsh22** [comment]
From conversations with Marshall we have decided to move forward with the proposed changes. Admin will have control over Special closure notice, and passes required Independently. 

@JLWade There will only be one status showing showing at any time. The yellow limited access icon will be shown in any situation where special closures is turned on.

**Comment by jpeersoxd** [comment]
Tested on TEST. No issues found. Moving to PO Review.

**Comment by JLWade** [comment]
working as expected - moving to done
