### ISSUE TITLE
DUP Admin-> Alignment issue with the Toggle on/off fields on Edit Facility pages

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-reso-admin#366]
Sceanrio:
* Navigate to the DUP Admin on TEST environment: https://d3jkh5unv9de6y.cloudfront.net/dayuse/
* Navigate to the Parks Management page.
* Select a Park and a Facility
* Now Select the option to edit the Facility. 
* Check how the toggle on/off fields displayed under the Publishing details section and When Are Passes Required? section.

Expected:
* The fields should be horizontally aligned.

Issue:
* the fields are all over the place without any alignment. 

![Image](https://github.com/user-attachments/assets/4312f794-ee48-45a4-a132-ddb379c5f6f7)

![Image](https://github.com/user-attachments/assets/07c3f365-e93c-4c7a-92c7-b1b84e2d8f9a)

**Comment by Christopher-walsh22** [comment]
Hey @manuji I have a fix coming for the top picture. I'm not sure what needs to be adjusted on the bottom picture; Please let me know what your seeing and I will get that a fix up for that right away.

**Comment by manuji** [comment]
Hi @Christopher-walsh22 , my apologies for not being clear about the second picture. It's the same issue, the toggle buttons are not aligned on a single line and scattered in a different horizontal alignment. If your fix is global I hope it's going to fix the alignment issue where toggle buttons exist.

**Comment by Christopher-walsh22** [comment]
My fix was specific to the facility. Which facility did you find this in TEST? Sorry I just cant see it, I even used my favorite design tool Paint! Let me know if you want to jump on a call and we can do a screen share to show me what is going on. 



![Image](https://github.com/user-attachments/assets/730d9c34-5948-4360-8a29-157a3cfea132)

**Comment by manuji** [comment]
Thank you @Christopher-walsh22 , today, I can't see it too. (sigh!)

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that this issue has been fixed.
